Removing AuthnContextClassRef to work with Clareity stores
16:13:23.566 - ERROR [edu.internet2.middleware.shibboleth.idp.authn.AuthenticationEngine:563] - Authentication failed with the error:
edu.internet2.middleware.shibboleth.idp.authn.AuthenticationException: Relying patry required an authentication method of [urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport] but the login handler performed urn:oasis:names:tc:SAML:2.0:ac:classes:Password

So that means your authentication request asked us to perform authentication with the context of 

urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport

We actually did since the site is behind SSL, but our support for explicitly stating that is pretty weak. Ideally, we need you to not request a specific authentication context in your request. It's not really needed since we are using SSL.